### ISSUE TITLE
ssh options don't seem to work

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#126]
I created a target, so that a user can only access it through a specific user :
```
[passhport@localhost ~]$ ./adminbin/passhport-admin target show centreon@centreon-front
Name: centreon@centreon-front
Hostname: 10.231.0.75
Port: 22
SSH options: -l centreon
Comment:
Attached users: toto
Usergroup list:
Users who can access this target: toto
All usergroups:
Member of the following targetgroups:
[passhport@localhost ~]$
```
Let's connect : 
```
[centreon@centreon-network-front ~]$ ssh passhport@10.231.0.74
Welcome toto.
Here is the list of servers you can access:
1 centreon@centreon-front 10.231.0.75
Type the number, name or hostname of the server you want to connect to. 1
Last login: Mon Apr 25 17:37:09 2016 from 10.231.0.70
[root@centreon-network-front ~]#
```
I'm connected as root, whereas I shouldn't, and should land as «_centreon_» user.

**Comment by elg** [comment]
In the passhport the code htere is a "ssh root@" so the -l option is not used.
We will have to add a username to the target infos (root by default) and remove this "root@" from passhport script.

**Comment by elg** [comment]
Actually, only the target name/IP is used by passhport script... not one option used. We have ot simply write it.

**Comment by elg** [comment]
Options are now applied.

By default, without a -l, it's root who is used. If there is one or multiple "l-" option, only the last one is used.
