### ISSUE TITLE
CentOS-RHEL 6/7 Support ?

### ISSUE THREAD

**Issue by ghost** [LibrIT/passhport#128]
Any chance find an install script for supporting CentOS/RHEL distro? I will try to adapt for my needs but I cannot guarantee to make it in short time.

**Comment by Raphux** [comment]
Hi,

Thank you for your feedback.

Well, even if the script mentions Debian, it actually works better with RHEL and CentOS.

I pretty sure it work smoothly on CentOS 7 for the moment.

You definitely should give it a try.

**Comment by ellagan** [comment]
Hi,

So let's give a try !

**Comment by elg** [comment]
We have successfully installed it on a redhat.  Still we were forced to use virtualenv and there is some more work needed to script it.

**Comment by elg** [comment]
We just need to do the doc. Everything is working now.

**Comment by Raphux** [comment]
https://docs.passhport.org/en/latest/installation-and-configuration/installation-on-centos.html

Closing.
