### ISSUE TITLE
Add an "test target access" functionnality

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#133]
It would be nice to be able to test if passport has access to a certain target

For example : 
\# passhport-admin access-test 192.168.2.9
Test results : passport has access to 192.168.2.9, with the followings : 
- root@192.168.2.9 (ssh option "-p 2223")
- user1@192.168.2.9 (ssh option "-p 2223)

Those configured access where refused : 
- user2@192.168.2.9 (ssh option -p 2223)

**Comment by elg** [comment]
The syntax should be more like:
passhport-admin  target access <targetname>

**Comment by elg** [comment]
should be able to let add the key after an error.

**Comment by elg** [comment]
After a long mono-debate with myself: the key fingerprints HAVE to be ignored for THIS test.

We can think to another way to test the fingerprints but in this case we just want to know if the server can connect to this hostname or not. We don't check if the server behind the hostname is trustable or not.
