### ISSUE TITLE
Make passhport available away from the passhportd node

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#149]
Wouldn't it be great to be able to have 3 differents hosts for each service : 
- passhport-admin
- passhportd
- passhport

The last one is currently sticky to the passhportd host, which, in some case, lowers the product experience quality.

**Comment by elg** [comment]
Problem seems limited to authorized_keys file which is directly edited by passhportd and used by passhport.

Case 1: We refuse to put passhport on a  different server
Case 2: passhportd copy / send the authorized_key file to the passhport server. (can cause network related issues and possible security issues). Can be handle by warning / error messages when we copy the file
Case 3: passhport copy a fresh file from passhportd server everytime he is launched (latency for user + same problems than above)
Case 4: passhport becomes a deamon with an API. An error is raised if their is an issue when copying the info on the authorized file.


Today I think we need to stay on the case 1. Same server. Eventually we can emulate the case 2 with a inotify cron who copy the file through scp everytime he is modified... But we are network dependant. 

In the best case, we should work on the Case 4... but that's either a new component or will be really complex to recode.

**Comment by elg** [comment]
Not in the roadmap today.
