### ISSUE TITLE
Admin client - Server interconnexion 

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#15]
Add an API call on the client side to manage user directly on the server. Using python module "Request" sounds the best.
Use case:
I launch the administration client.
I create a user
The client call the API to create the user
The server create the user and return an error/success code.
The client indicate the result on screen.

The use case has to be declined to all the actions possible between client and server on the USER module

**Comment by VeryTastyTomato** [comment]
I think I did all the tasks for this issue.
