### ISSUE TITLE
make the python-run-env path configurable

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#150]
The python-run-env path should be customisable, in a conf file for example, instead of hardcoded in the source.

**Comment by elg** [comment]
Which component? It is already for passhportd which include passhport, maybe for passhport-admin ? But since it's the user who launch it... I don't see the point.

**Comment by Raphux** [comment]
My bad, I did a grep, and miss-red the result, thinking that the path was inside the source… 

Sorry for the noise. Closing…
