### ISSUE TITLE
Modify passhport installation script to allow database type selection

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#199]
Today we are supposed to handle mainly:

postgresql
mysql
sqlite
oracle.

I think we can forget oracle. But since there is some potential limitations with sqlite (for large installation or advanced DB features), it would be good to offer the user a choice on database type during installation.

**Comment by Raphux** [comment]
I think that the purpose of the automatic installation script is to ease the discovery of the project and/or to have a quick base installation. We should KISS, but enhance the documentation so that the user can easily find references on how to use other databases.

**Comment by elg** [comment]
Be it.
