### ISSUE TITLE
Catch error when no user exist in DB

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#209]
Changed from sqlite to postgresql, ran db_create.py smoothly, but forgot to add a user, so when I connected to passhport, got this unusefull message : 
```
[>] ssh passhport@10.x.x.x
Traceback (most recent call last):
  File "/home/passhport/passhport/passhport/passhport", line 198, in <module>
    username).split("\n")
AttributeError: 'int' object has no attribute 'split'
Connection to 10.x.x.x closed.

[>] 
```

Maybe we should try to catch and display a good message ?

**Comment by elg** [comment]
To test after the merge of ew4321 patch.

**Comment by elg** [comment]
Tested. I'll change the error message since it also happen when the connection to passhportd fail (passhportd not reachable for any reason: network, SSL certificates or even not launched at all).
