### ISSUE TITLE
When directly connecting to a target ("ssh passhport@bastion myhost"), ctrl commands are not correctly catched

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#229]
Let's say I connect directly on a target : 
```
$ ssh passhport@10.0.0.1 mytarget
Last login: Thu Nov  9 17:11:32 2017 from 10.0.0.84
Linux 3.2.83.
root@mytarget:~# 
```

Now if I do CTRL+r (revers bash history search), the CTRL+R is printed : 
`root@mytarget:~# ^R`
and I can't search bash history

If I press CTRL+c, I quit bash, and connection is closed : 
```
root@dgalx270:~# ^C
[raphux@briareos4 <0> 05:12 ] (/var/tmp) 
[>] 
```
This bug does not appear when I manually select an host in the host list after a simply connect to passhport : 
```
$ ssh passhport@10.0.0.1
[…]
Type the number, name or hostname of the server you want to connect to : mytarget
Last login: Thu Nov  9 17:07:52 2017 from 10.0.0.23
Linux 3.2.83.
root@mytarget:~# 
(reverse-i-search)`':
root@mytarget:~# 
```

**Comment by Raphux** [comment]
Because «ssh» command interpret the last argument as a command, it removes the interactive mode of ssh. To force enable the interactive mode, use the `-t` switch. It then works perfectly.

**Comment by Raphux** [comment]
Need to document that.

**Comment by elg** [comment]
commit a6372f4
