### ISSUE TITLE
Add a public sshkey management

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#23]
When I delete a user, his public key has to be deleted too from the authorized key.

**Comment by elg** [comment]
Decision: 
We think that passhport CAN'T duplicate users keys. If it does it, it's a bug. So when we delete a key, we delete only one: so if someone add a key manually, passhport don't delete it. 
Put a warning message when deleting a key and it still exist.

**Comment by VeryTastyTomato** [comment]
Done
