### ISSUE TITLE
Latency when deleting a user

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#233]
If a user is in a usergroup, we try to remove the user from all the targets accessible via this usergroup.

We should remove the user only from target he is directly attached (cf line 409 in views_mod/user and do the same for targets)

**Comment by elg** [comment]
Need some tests

**Comment by Raphux** [comment]
Perfect.

```
[passhport@dev ~]$ time passhport-admin user delete -f raphael.berlamont@librit.fr 
[…]
OK: "raphael.berlamont@librit.fr" -> deleted

real	0m0.841s
user	0m0.419s
sys	0m0.048s
[passhport@dev ~]$
```
