### ISSUE TITLE
passhport-admin checkaccess doesn't work

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#243]
This is what I have when I try to use the checkaccess command. (I can access the host otherwise) :

`ERROR:127.0.0.1	passhport-testmdp	Error with this ssh command: ssh -p22 root@127.0.0.1  -o PasswordAuthentication=no -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=10 echo OK`

**Comment by elg** [comment]
I can't reproduce it.

**Comment by elg** [comment]
added some more debug. repoen if needed.
