### ISSUE TITLE
SSL Certs after fresh install

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#246]
Create a new system, install passhport (with script).

$ passhport-admin user list
ERROR: Connection error. Check your configuration.
HTTPSConnectionPool(host='bastion.anydomain.tld', port=5000): Max retries exceeded with url: /user/list (Caused by SSLError(CertificateError("hostname 'bastion.anydomain.tld' doesn't match either of 'localhost', 'passhport', 'passhport.passhport.org', 'passhport.librit.fr', 'bastion', 'bastion.passhport.org', 'bastion.librit.fr'",),))

**Comment by elg** [comment]
This is certainly duplicate of #191 
Anyway it's a blocker for rapid adoption (it needs user to understand where the problem is before even testing). I think it should stay simple and automated: no ask to the user, just  using hostname -f is not enough? Else use localhost can be a good solution I think.

**Comment by Raphux** [comment]
Corrected in commit #ead3da9d65ad72ec90fe74bf1ec1f39bfc753ded .
