### ISSUE TITLE
Save multiple version of password file

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#259]
When passhport change password of a machine, it may be a good idea to write a backup of the file, to have an history (or/and just a backup).

**Comment by elg** [comment]
It's really too short to explain the goal.

I guess it could be usefull in the case of a target is restored from an old backup. So we still can have the password to access to it.

So I purpose to add a timestamp to the filename.

Problem will be to rotate this and avoid to keep too many copies. So we need to add a limitation, maybe in days? 

We have to think the limit, the way to rotate etc. Please add the reason of this enhancement to allow us any implementation.

**Comment by Raphux** [comment]
Passwords (and history) are now stored into Database.
