### ISSUE TITLE
Used ProxyCommand - no cible

### ISSUE THREAD

**Issue by incierk** [LibrIT/passhport#347]
Hello

First of all, I congratulate you on this product. 

But I have a problem. In my virtual network I installed a passport machine and two target machines (target serveur et no target server ). And I added the target server in the Passhport database and it works. But the no target server, I did not add in the Passhport database, I can access via passhport server (ProxyCommand ssh tunnel command). Normally, we must not access machines not declared in passhport.

For exemple : 

Host Passport
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  Hostname IPPublic
  User test

Host NoTarget
  UserKnownHostsFile ~/.ssh/notarget_known_hosts
  Hostname IPprivate
  User test
  ProxyCommand ssh -W %h:%p Passhport

Normally I do not have to access this unreported server in the Passport database ?

Do you have a solution to this problem?

Thanks

**Comment by elg** [comment]
Hi!

Thanks for this feedback. Just to be sure I understand correctly, I'll redescribe your test case.

You have: 

- One passhport machine (we name it P),
- one machine named A with the P public sshkey installed,
- one machine named B with the P public sshkey installed,
- one ssh client named C.

You add A to passhport. So from C, you can access A by the passhport menu.
You didn't add B to passhport. Still, from C, by using Proxycommand, you're able to access B via P.

Can you confirm the scenario? (I'm not sure if we deactivate this on openssh server configuration or not, I need to check)

**Comment by incierk** [comment]
Hi, 
Thanks for your reponse.

Scénario :
One passhport machine (we name it P),
one machine named A with the P public sshkey installed, (on the machine P and A public sshkey installed for user test)
one machine named B public sshkey  installed(only on the machine B for user test)
one ssh client named C (same keyprivate/keypublic for A and B)
I add A to passhport. So from C, I can access A by the passhport menu.
I didn't add B to passhport. Still, from C, by using Proxycommand, I am able to access B via P.

Thanks

**Comment by elg** [comment]
Hi,

After some tests, I'm not able to reproduce something I can consider as issue. Can you give me the exact commands you are using to put ssh keys on servers, create targets, connect via ssh etc. 
I'm not sure if I understand who is owner of which key in your example.
Can you do a more step by step explanation to reproduce the issue?
