### ISSUE TITLE
Get lastlogs from API doesn't work

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#348]
**Describe the bug**
API call to retreive last log doesn't work as expected. It's not the last logs that are retrieve.. For the mooment, I don't understand par the date pattern of the returned logs.

**To Reproduce**
1 - Connect to a server through PaSSHport, type some commands, then exit.
2 - Connect to a server that can call the passhportd API
3 - Get the log with this command : curl https://localhost:5000/user/lastlog/raphael.berlamont@librit.fr | grep Logfile | sort | tail
4 - See that the last logs are from several months ago.

**Expected behavior**
I should get the last connections

**Comment by elg** [comment]
Corrected (was the 500 first instead of 500 last.
