### ISSUE TITLE
Docopt module not found

### ISSUE THREAD

**Issue by okajimmy** [LibrIT/passhport#391]
After installation (manual and automatic one), we got a "docopt" ModuleNotFoundError error as we execute a passhport-admin command.

so to fix the issue, we need to install the "docopt" module via pip, as bellow:

-># /home/passhport/passhport-run-env/bin/pip install docopt

so thanks to add this to main documentation.
Regards

**Comment by elg** [comment]
Hi, thanks for this feedback. Can you tell me on which OS you are? (I've tested that few days ago with a centos/debian and automatic script without issue)

**Comment by okajimmy** [comment]
Am on Debian system 10.1 system, I confirm that it's working like a charme on a CentOS 7, in both installation mode.

**Comment by elg** [comment]
Ok this was a lack on requirements.txt. I've updated that. Weird: the debian doc use this file, which is good, while centos doesn't...

Thanks !
