### ISSUE TITLE
Cryptography module installation

### ISSUE THREAD

**Issue by okajimmy** [LibrIT/passhport#392]
**Describe the bug**
when trying to install passhport using the manuel way, using "https://docs.passhport.org/en/latest/installation-and-configuration/installation-on-centos.html"
an Import error occurs, when trying to create the database using : db_create.py
=> ImportError: No module named 'cryptography'

**Solution**
Install the module "cryptography" when installing other modules using : passhport-run-env/bin/pip install cryptography.

Regards

**Comment by elg** [comment]
Hey ! 
Can you confirm you have this issue with centos? I've made the correction but I can't find how this can be wrong on debian.

**Comment by okajimmy** [comment]
Oh sorry my bad, yeah i confirm that the issue concern Centos 7. (I forgot to mention it)
