### ISSUE TITLE
Direct ssh connection Problem

### ISSUE THREAD

**Issue by okajimmy** [LibrIT/passhport#393]
**Describe the bug**
when executing a direct ssh connection via passhport host, using : 
>> ssh passhport@gateway RemotSV_hostname

I noticed that the script : /home/passhport/passhport/passhport/passhport-connect.sh is executed infinitely after exiting the session using ^C  

**To Reproduce**
Eonnect to a remote server using : 
>> ssh passhport@gateway RemotSV_hostname

Exit the opened session using: Ctrl+C
>> ^C

**Expected behavior**
Execute : 
>> ps aux | grep passhport-connect.sh | wc -l
many times, you will notice that the script is executed delicately.

**Comment by elg** [comment]
Ouch this is a big one. I'll try  to reproduce as soon I got my hands on a computer. I'll keep you update.

**Comment by okajimmy** [comment]
Okey think there are many problems concerning this brick (direct connection) of the software.

1- As described, an problem when exiting the connection.
2- When connected directly, there is a message assuming that the TERM environment variable is not loaded, when making a "clear" command.
3- The shell behave differently comparing to a standard ssh connection via passhport (by using the interactive mode)

**Comment by elg** [comment]
1. This is a complex problem wich will need time. Best is to deactivate autoreconnect (KEEPCONNECT to false in passhport.ini). This will avoid the issue but you will need to reconnect after every interactive connection.
2 &3. If I understand correctly, it's a ssh technical limitation well known. You can workaround this via option "-t" when you launch ssh (ssh -t passhport@bastion target). Since we are using a vanilla opensshd for security reasons, we will not be able to change this on the server side.

Hope this help.

**Comment by romfleur** [comment]
Hi elg, any ETA for the resolution of (1) ?
We would like to connect using Ansible / scripts.

**Comment by elg** [comment]
Should be ok now. The issue was tricky, the solution trivial. Don't hesitate to reopen an issue if it is not OK for you.

**Comment by romfleur** [comment]
Hi, nice, @Raphux will try it asap 👍

**Comment by Aguay-val** [comment]
Hey @romfleur ,

How did you manage to launch a playbook through passhport with ansible ?
I can't figure out how it's possible...

If you you can reply it would be awesome.

**Comment by asetiam** [comment]
Hey,

I wrote a script that generates ansible inventory from passhport database.
You get such a file:

[target group name]
targetname ansible_host=targetip

[target group name:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -t -W %h:%p -q -p {passhport listening ssh port} passhport@yourip/fqdn"'

All of our playbook run now through passhport.




________________________________
De : Aguay-val <notifications@github.com>
Envoyé : lundi 25 mai 2020 14:46
À : LibrIT/passhport <passhport@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [LibrIT/passhport] Direct ssh connection Problem (#393)


Hey @romfleur<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fromfleur&data=02%7C01%7C%7Cbcde73be060f43e816cd08d800a99b9c%7C1a5208c4058247ae81a51d3a42d1cbe6%7C0%7C0%7C637260075742882040&sdata=oC84akw1axSeC1reYvJcC%2Ba%2FWnXY5BOmUicpBDup5fo%3D&reserved=0> ,

How did you manage to launch a playbook through passhport with ansible ?
I can't figure out how it's possible...

If you you can reply it would be awesome.
