### ISSUE TITLE
Debian 10 useradd

### ISSUE THREAD

**Issue by MyTheValentinus** [LibrIT/passhport#394]
Hello,
Today i try passhport on a fresh install of Debian 10 and I encountered a bug when the script try to add user passport.

**Describe the bug**
`useradd` commant does not exist in debian 10.

**To Reproduce**
Launch automated install script on recent Debian 10.

Thanks

**Comment by MyTheValentinus** [comment]
Edit: You need to specify full path:  /usr/sbin/useradd

**Comment by elg** [comment]
Hey,

Thanks for this feedback. We will correct that :)

**Comment by elg** [comment]
https://github.com/LibrIT/passhport/commit/bfaf8275d1e96d9adc63adb83750e4c6c26d25cd
 Wrong issue number in the commit message.
