### ISSUE TITLE
Current session not listed

### ISSUE THREAD

**Issue by MyTheValentinus** [LibrIT/passhport#395]
**Describe the bug**
When i go to `/connection/ssh/current` and i have multiple ssh connections open, the API do not response current active sessions.
Same for others API endpoints that use active connection.

It is normal ? reserved to pro version ?

Thanks

**Comment by MyTheValentinus** [comment]
Ok, i just push all .cron files from tools folder inside `/etc/cron.d` and restart my cron service, but after this current sessions no appear to the API.
Do you have logrotate template for all log to be compress after some days of closed ssh session ?

**Comment by MyTheValentinus** [comment]
When i execute script `/home/passhport/passhport/tools/garbage-collector.sh` the return was "No active connection."
I'm connected to standard SSH server via passhport server on port 22 without any SSH options.

**Comment by elg** [comment]
We don't use logrotate on production : the logs are stores in daily directory and we are using external process to archive it. (But we should provide a logrotate example indeed, we will look into it).

Are you using SQLite ? I suspect a bug on date calculation.This API call us tested against postgresql. If you confirm you are on SQLite, I should bé able to reproduce.

**Comment by MyTheValentinus** [comment]
Hello @elg , yeah i use sqlite for the moment (test purpose)

**Comment by elg** [comment]
Ok. I'll look into it in the same Time that MySQL. Consider pgsql for tout tests.

**Comment by MyTheValentinus** [comment]
Humm, will you bear on the long term mysql ?
pgsql is good, fast etc.. But on long term is hard to maintain DB, cleanup index etc..

**Comment by elg** [comment]
No SQL databases judgement from us :)

However, the feedback de receive is more often for pg. We still support MySQL and SQLite but we have less feedbacks and our tests don't cover this part entirely. We plan to do campain tests for main releases on the three databases. 

But as said, I'll look into it asap !
