### ISSUE TITLE
[Question] Proper method to update

### ISSUE THREAD

**Issue by MyTheValentinus** [LibrIT/passhport#400]
Hello,
What is the best method to update my current working env of passhport ?
Thanks

**Comment by elg** [comment]
Nice question... Work in progress :). Our process is currently based on enterprise customers. However, we are building the first steps for the next open source version.

We provide a "stable" branch and releases.
We will change the doc to encourage the open source version users to use this one.
In the future, for complex cases, the release will provide a script to update the databases/config files.

FYI, we will provide a new stable version (corresponding to the current master) before november 15. This version will be tested on the three databases. There will not be a lot of new features on the open source version but it will prepare some nice things for next one.

If you want to use master: you'll have to git update and work around the databases updates (we are currently using flask migrate). It's sometimes complex, but with some basic databases administration/architecture knowledge it should be ok.

Is this answer ok for you? I know this is not what you would expect.

**Comment by elg** [comment]
Ho and I forgot: If you have knowledge on packaging and some time, there is #20 open for contributions ;)

**Comment by MyTheValentinus** [comment]
I see, i see ;) If I have time I will probably work on this project.

**Comment by MyTheValentinus** [comment]
@elg Do you have any chat platform for contributors ? Like Telegram ?

**Comment by elg** [comment]
https://t.me/PaSSHport

**Comment by MyTheValentinus** [comment]
Thanks, but is channel not a chat ?
