### ISSUE TITLE
Error install script

### ISSUE THREAD

**Issue by augustechartre** [LibrIT/passhport#403]
**Describe the bug**
When I tried to install passhport I have this error:
```
passhport-install-script-debian.sh: 11: /etc/bash_completion.d/passhport-admin: Syntax error: "(" unexpected (expecting "fi")
```
**To Reproduce**

```
sudo wget https://github.com/LibrIT/passhport/archive/v2.0.0.tar.gz
sudo tar -xvf v2.0.0.tar.gz
cd passhport-2.0.0/tools
sudo sh passhport-install-script-debian.sh
```
Thanks,

**Comment by elg** [comment]
Sorry I didn't saw this. I'm looking to that very soon.

**Comment by elg** [comment]
Hi,

I can't reproduce this. I think it's cause of the "sh" you put in front of the installation script. It is supposed to be launched as bash (so replace sh by bash or simply launch it without any shell in front of it.
