### ISSUE TITLE
Passhport & MobaXterm SSH-Browser

### ISSUE THREAD

**Issue by Matkill** [LibrIT/passhport#406]
Hi,

Just noticed that SFTP ssh-browser is not working while remoting a server through Passhport. Is there a way for it to work ? did not find any mention of that in the documentation.

Thanks

**Comment by elg** [comment]
hi,

SFTP Is not currently supported. You have to use SCP protocol.
There is an API call that provide an easy way to SCP. the enterprise version WEBUI use this API to allow file  transfert via a browser.

**Comment by elg** [comment]
I've never used MobaXterm but it seems to support protocol overwrite for scp. 
The screenshot here https://github.com/mikecroucher/Intro_to_HPC/issues/2

Is that working for you?

**Comment by Matkill** [comment]
Hi, thanks for your answers.

Well no it does not change anything in changing from sftp to scp. I think this is because of the way of where i added the connection.

To have one connexion per server, but in using Passhport for each connection, i used a trick in MobaXterm. In fact for each connection the remote host is Passhport with passhport user, and i filled the "Execute Command" after having initiated the connection to put the server name (known by Passhport) to connect to the server. Like that MobaXterm connects to Passhport and then "type" in the shell the server i put in the "Execute Command" like if i typied it myself once connected.

I think this is because of the way to work i'm having this issue.

I don't know if you have any ideas to add X server connections in a tree to connect directly to the servers but through Passhport. The trick explained above is the only thing that i found for it to work.  SSH GAteway option does not work because Passhport is using its own key to connect to servers, and ssh gateway is using the user key so i can't use that option...

**Comment by elg** [comment]
Hi,

If I understand correctly, I think you do it right. ( ssh t -passhport@bastion servername )

Maybe you could add some new connection especially for SCP transferts...
