### ISSUE TITLE
Check the pattern email

### ISSUE THREAD

**Issue by VeryTastyTomato** [LibrIT/passhport#44]
It would be good to check if the email submitted when creating a user is valid. Using regex is a bad idea (see http://www.bortzmeyer.org/arreter-d-interdire-des-adresses-legales.html), but sending an verification email may be uncomfortable, although it seems to be the best solution.

**Comment by elg** [comment]
No way tosend an email. We don't care if the email format is not a good one.
Le 11 juin 2015 17:18, "VeryTastyTomato" <notifications@github.com> a
écrit :

**Comment by VeryTastyTomato** [comment]
For now yes, but maybe in the long term it could be interesting ? If not, the issue can be closed then.

**Comment by elg** [comment]
Can become an option in a veryblong term. I really think that's too much
today. Let's close the issue.
Le 11 juin 2015 18:38, "VeryTastyTomato" <notifications@github.com> a
écrit :

**Comment by VeryTastyTomato** [comment]
Oh it was just a suggestion, I wasn’t working on that at all. I talk about that to remember in the future.
