### ISSUE TITLE
Strings’ concatenation

### ISSUE THREAD

**Issue by VeryTastyTomato** [LibrIT/passhport#47]
The best way in python is to use the method `''.join()` instead of the `+` operator (see https://www.python.org/dev/peps/pep-0008/#programming-recommendations and http://stackoverflow.com/questions/2133571/most-pythonic-way-to-concatenate-strings)

**Comment by elg** [comment]
Join and + are 2 different functions used for different things.

joins is to concatenate strings from a lsit, while + is to concatenate 2 strings objects.
