### ISSUE TITLE
Inconsistence in URL for editing

### ISSUE THREAD

**Issue by VeryTastyTomato** [LibrIT/passhport#48]
In the module user, the URL for editing a user is:

http://127.0.0.1:5000/user/edit

but in the module target, the URL is:

http://127.0.0.1:5000/target/edit/

with a trailing slash. It’s a bit problematic because when we use the URL for editing target without the trailing slash, flask raises:

> FormDataRoutingRedirect: A request was sent to this URL (http://127.0.0.1:5000/target/edit)
> but a redirect was issued automatically by the routing system to "http://127.0.0.1:5000/target/edit/". 
> The URL was defined with a trailing slash so Flask will automatically redirect to the URL
>  with the trailing slash if it was accessed without one. 
> Make sure to directly send your POST-request to this URL since we can't make browsers
> or HTTP clients redirect with form data reliably or without user interaction.

> Note: this exception is only raised in debug mode

**Comment by elg** [comment]
go for adding trailing slash everywhere. Sounds ok to you?

**Comment by VeryTastyTomato** [comment]
Well I did exactly the opposite. x)

**Comment by elg** [comment]
After discussion
