### ISSUE TITLE
Is PaSSHport compatible with Red Hat 8 ?

### ISSUE THREAD

**Issue by lsystem75** [LibrIT/passhport#552]
Hi,

Can you please tell me if PaSSHport is compatible with Red Hat 8 ?

Thank you,

**Comment by Raphux** [comment]
Hi there,

it should, but haven't tested yet.

We don't have RHEL8 licences to test, so I'll test with CentOS8 and will come back here with results.

**Comment by Raphux** [comment]
@lsystem75 , you may try the new [CENTOS8 installation script](https://github.com/LibrIT/passhport/blob/master/tools/passhport-install-script-centos8.sh).

**Comment by lsystem75** [comment]
Hi Raphux,

Thank you very much for the feedback, I'll try it.
