### ISSUE TITLE
Put all compat file into one

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#56]
We want to have less duplicated code for this.

**Comment by VeryTastyTomato** [comment]
The issue I had with relative imports is hopefully resolved. We have to move the script passhport-admin upper in the tree.  We should carefully think about the organisation of modules and packages before continuing, in order to avoid import’s issues in the future.

**Comment by elg** [comment]
After discussion, this issue remains.
We have to re-think the code organization. I put that on another milestone.

**Comment by VeryTastyTomato** [comment]
This issue is not relevant anymore.
