### ISSUE TITLE
Avoid elif on passhport-admin

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#58]
Even If I've said it was a good way to do it, the code become too complex on argument parsing with a lot of if and elif.
We need to find a new way to do it. TIdeas I have:

1. Read the docopt doc / ask community about this problem.
2. Create a simple If / elif on the first level of command and then call function for subcommands.
3. Looking for a docopt replacement.

**Comment by VeryTastyTomato** [comment]
Done awesomely by elg.
