### ISSUE TITLE
No such user in PaSSHport database. (https API 500 error)

### ISSUE THREAD

**Issue by antoinesamsonacetiam** [LibrIT/passhport#581]
We are running for months with success a clustered passhport installation:
Two nodes
Apache / Postresql backends
Master/Slave postgresql streaming replication (slave is in read only, generates some passhport(d) warnings of coarse but works fine)

Yesterday, after adding some target using CLI, we found slave node to answer:

**No such user in PaSSHport database.
tip: it can be a SSL certificate misconfiguration.**

While  debugging this issue, we can see that:

- API was correctly responding on slave node for basic requests:
curl -k https://localhost:5000
passhportd is running, gratz!

but sends back 500 error for 
127.0.0.1 - - [18/Feb/2022:10:04:51 +0100] "GET /user/accessible_idtargets/mylogin HTTP/1.1" 500 290 "-" "python-requests/2.21.0"

- As long as we delete the previously added target (wich has noting specific compared to other already declared targets), API works correctly on slave node
127.0.0.1 - - [18/Feb/2022:10:10:46 +0100] "GET /user/accessible_idtargets/mylogin HTTP/1.1" 200 80209 "-" "python-requests/2.21.0"

Master node works without any issue anytime.

In fact, just adding a target doesn't generate the issue but once added to the requested target group it fails.
AND ONLY on one specifice target group XXX

If I create the same target, and add it to another targetgroup first, then add it to requested target group => no issue

We went to conclusion that only on slave node:
if your login target available list contains "group in a group" acces heritage, it fails the GET /user/accessible_idtargets/mylogin request

**Comment by elg** [comment]
Hi,

If I understand correctly, the issue appears only on the slave?

Can you confirm that the issue appears whatever the username and Target name and Targetgroup name are? (To be sure you're not using an internal reserved name ... But I doubt it)

I'll take a look to the code to see if I see something obvious.

If you have a complete way to reproduce it from a fresh install? (Incl. The cluster conf)

Thanks
