### ISSUE TITLE
Install on Debian 11

### ISSUE THREAD

**Issue by PONCH0S** [LibrIT/passhport#582]
Hello,

I've looked for a fix by myself before comming here to post this message. I hope this is the good place to do it. If not my apologise ...

This project seems to be the one I was looking for. I've read in the documentation that is compatible with Debian 8, 9 and 10 and meaby with 7 too. Anyway I've tried to set up on Debian 11 (in case it would work) through the script and I get this error message (in red) when I run de service :
![2022-02-25_08h24_04](https://user-images.githubusercontent.com/100370483/155673425-7634268c-042b-4b79-a9a5-63d584f1079f.png)

Is there a way to find a solution before testing the install process on Debian 10 ?

Thanks.

**Comment by Raphux** [comment]
Hello !

Thank you for this issue, and you're right : actually, Debian 11 is not supported. This is on the roadmap and I'll keep this thread updated when this will be the case.

**Comment by PONCH0S** [comment]
Thanks for your fast reply. I'm going to try with Debian 10 until the release of new version.

**Comment by Raphux** [comment]
Hello,

I guess this wasn't working also for previous version of debian either.

We updated the requirements.txt file, to fix a version of the itsdangerous lib. Newer version of that lib seems to be non compatible.

It should now work smoothly.

Thx to @elg for the tips.
