### ISSUE TITLE
Bug report urlencoded string

### ISSUE THREAD

**Issue by IAmAStealer** [LibrIT/passhport#599]
Hello,

Using prompt create for a targetgroup, but I assume for other item as well, you can create an object like : %20%20
This object in a list will be printed as %20%20 but after that it cannot be deleted anymore : %20%20 for example using API or prompt will end up in trying to delete a two whitespace string.

**Comment by elg** [comment]
Hi,
Can you provide the exact prompt to reproduce it please? 

I have noticed this issue on some system but people are using the web interface and are unable to reproduce

Thanks

**Comment by IAmAStealer** [comment]
Sure :

`$ passhport-admin targetgroup create
Name: %20
Comment: 
OK: "%20" -> created
$ passhport-admin targetgroup list
%20
%20%20
$ passhport-admin targetgroup delete %20
ERROR: No targetgroup with the name " " in the database.
$ curl -s -k "https://127.0.0.1:5000/targetgroup/delete/%20"
ERROR: No targetgroup with the name " " in the database.
`

**Comment by elg** [comment]
Thanks for the feedback (I got a lot of feedbacks about this issue, without beeing able to reproduce... who call his targets "%20" anyway ? 😉 ). I think possible this issue exists on similar cases.

Still I've made a correction either for targets, users, targetgroups, usergroups.

Feel free to re-open if needed.

**Comment by mqu** [comment]
> I have the same problem when I try to delete user (username = [toto@example.com](mailto:toto@example.com)). Then, I have this answer:

same here too, having user in the form of email address and target in the form of "user@hostname".

passhport-admin CLI is not working correctly now ; don't know how to get running version.
