### ISSUE TITLE
Installation Doc / Wiki

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#6]
A installation documentation must be written with all packages to install and some initial commands to test the application.
All of this information has to be a on a single github wiki page.

**Comment by VeryTastyTomato** [comment]
These instructions are written for Debian 8.0.

Before installing passphport, you need to install the following packages:
— git;
— python3-docopt;
— python3-flask;
— python3-flask-sqlalchemy;
— python-flask-migrate;
— python-migrate;

Then enter the following command:

	$ git clone https://github.com/LibrIT/passhport.git

and, after going in the folder passhport, launch the script db_create.py:

	$ ./db_create.py

Now you can start the server using the command :

	$ ./passhportd

**Comment by elg** [comment]
I'm not sure that Git neither Curl are usefull. Raphux will create the wiki page, I guess he can try wihtout this dependencies (downloading the zip from the github interface)

**Comment by elg** [comment]
Git and Curl are used to develop/test... Means that maybe we need a "Development environment installation" doc page too ? or maybe a simple paragraph.

**Comment by elg** [comment]
Last comment, on Debian 7, the dependencies aren't packaged... So maybe add a simple line like:
"For unsupported distribution, you can try to use pip to install the dependencies". PiP  works well on debian 7 for example.

**Comment by VeryTastyTomato** [comment]
After testing, if you use Python 2.7, you need to install python-docopt instead of python3-docopt (which is for Python 3).

**Comment by elg** [comment]
So we need to create a documentation for Debian 8, using packages about python 2.7 with remarks for:
 * python3 (saying that it python3-XXX packages have to be installed)
 * Debian 7 (saying that pip has to be used)

**Comment by VeryTastyTomato** [comment]
The package $python-requests is also needed.

**Comment by elg** [comment]
I'll takeover this one.

**Comment by VeryTastyTomato** [comment]
For testing we use the module pytest, installed with the following packages:
$ sudo apt-get install python-pytest python3-pytest

**Comment by elg** [comment]
Doc wiki is simply initiated... Still the issue should be pushed in next iteration.

**Comment by VeryTastyTomato** [comment]
In fact, we use the module nosetests to do unit tests, so the package needed is:

    sudo apt-get install python-nose

**Comment by VeryTastyTomato** [comment]
The following command needs to be launched as well:

    pip install future

**Comment by elg** [comment]
Linked with  #128

**Comment by Raphux** [comment]
With docs.passhport.org that contains chapters for installation under Debian and CentOS, this issu can be closed.
