### ISSUE TITLE
File are missing : manage_targetgroup

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#60]
I miss some files. I guess you forgot to add them. Can you add them ASAP if you have them please.
$ ./passhport-admin 
Traceback (most recent call last):
  File "./passhport-admin", line 66, in <module>
    import manage_targetgroup.prompt_functions as targetgroup_prompt
ImportError: No module named manage_targetgroup.prompt_functions

**Comment by VeryTastyTomato** [comment]
Done
