### ISSUE TITLE
Bug concerning API for usergroup

### ISSUE THREAD

**Issue by IAmAStealer** [LibrIT/passhport#600]
**Describe the bug**
I encountered a bug within the API and trying to get help to fix my command or fix the code.
To me the problem seem to come from the SQL or edit endpoint for the usergroup.
while reading the code I cannot see the error

**To Reproduce**

Create one usergroup and one targetgroup for comparison ( any method is ok for creation )
```
curl -k -X POST -d 'name=testUG&comment=comm' "https://127.0.0.1:5000/usergroup/create"
OK: "testUG" -> created
curl -k -X POST -d 'name=testTG&comment=comm' "https://127.0.0.1:5000/targetgroup/create"
OK: "testTG" -> created
```

Edit with a new_name because it must be renamed for whatever reason
```
curl -k -X POST -d 'name=testUG&new_comment=comm&new_name=test2UG' "https://127.0.0.1:5000/usergroup/edit"
sqlalchemy.exc.ArgumentError: subject table for an INSERT, UPDATE or DELETE expected, got Column('name', String(length=256), table=<usergroup>).

curl -k -X POST -d 'name=testTG&new_comment=comm&new_name=test2TG' "https://127.0.0.1:5000/targetgroup/edit"
OK: "testTG" -> edited
```

The SQL sends an error when trying to rename the usergroup but not the targetgroup.

**Expected behavior**

```
curl -k -X POST -d 'name=testUG&new_comment=comm&new_name=test2UG' "https://127.0.0.1:5000/usergroup/edit"
OK: "testUG" -> edited
```

Regards,

**Comment by elg** [comment]
Hi,
Indeed, the logs are cryptic :) I'll have a look.

**Comment by elg** [comment]
Nice catch. Apparently nobody is modifying usergroups since the bug exists since a while.
