### ISSUE TITLE
Create systemd / initV startup scripts...

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#80]
Raphux LOVES systemd. So it's for him.

We have to install them during the installation script, and to test them on debian 7 and 8 at least. The scripts only launch the passhportd service.

**Comment by Raphux** [comment]
Just for debian 8 and 9 now.

**Comment by Raphux** [comment]
Resolved for systemd in #219 .
Closing. If we need initV init script, we'll open a new issue.
