### ISSUE TITLE
Miss a human readable message when the database is missing

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#81]
When the db_create.py hasn't been launched, the error message is too complexe. We have to raise a message like:
Error: Database connexion failed. (hint: go check the file "passhportd/config.py" to find the app.db

**Comment by VeryTastyTomato** [comment]
My solution is to not launch the server passhportd if the db.create.py script has not been used. Therefore, if we try to use passhport-admin in this situation, it will just print the error message that tells that connection with the service has been aborted.
